### ISSUE TITLE
facebook disable account when use this tool

### ISSUE THREAD

**Issue by waves98** [mkdirlove/FBTOOL#14]
how to solve this problem, when we use this tool facebook disable our account.
and then tool cant work without facebook account.

**Comment by rarvau2002** [comment]
Same problem

**Comment by mkdirlove** [comment]
must use new facebook account before using this tool!!!


old facebook account can be disable if you use it to login in this tool

**Comment by mkdirlove** [comment]
i'm going to update and upgrade the tool from Python2 to Python3, add some new features, and fix some major bugsssss.
