### ISSUE TITLE
Johnny CLONE?

### ISSUE THREAD

**Issue by revdeluxe** [mkdirlove/FBTOOL#36]
I though this is a decrypting JS to PYTHON.
but it hurts when you expect too much. not being rude but.
you should have said FBCRACKINGTOOL, on the readme file.

**Comment by shohan1122** [comment]
I though this is a decrypting JS to PYTHON.
but it hurts when you expect too much. not being rude but.
you should have said FBCRACKINGTOOL, on the readme file.

**Comment by revdeluxe** [comment]
> I though this is a decrypting JS to PYTHON. but it hurts when you expect too much. not being rude but. you should have said FBCRACKINGTOOL, on the readme file.

???
