### ISSUE TITLE
hello, I have a suggestion for your tool. It would be interesting to put a function to get the user agent from the user's browser. Thus, facebook would not block the account login.     It would also be interesting to put an alert for people to disable the VPN when they use the tool for precisely the same reason.

### ISSUE THREAD

**Issue by f1gur4nt** [mkdirlove/FBTOOL#8]
hello, I have a suggestion for your tool. It would be interesting to put a function to get the user agent from the user's browser. Thus, facebook would not block the account login.

  It would also be interesting to put an alert for people to disable the VPN when they use the tool for precisely the same reason.

**Comment by mkdirlove** [comment]
i'm going to update the tool from Python2 to Python3 so that i can put some new functions for new features.

I'll try my best for your suggestion bro.

i liek your idea
